export const  cities = [{
    name: "Sehwān",
    cName: "Pakistan"
   }, {
    name: "Abbottābād",
    cName: "Pakistan"
   }, {
    name: "Shikārpur",
    cName: "Pakistan"
   }, {
    name: "Minakuchi",
    cName: "Japan"
   }, {
    name: "Karak",
    cName: "Pakistan"
   }, {
    name: "Abha",
    cName: "Saudi Arabia"
   }, {
    name: "Ninomiya",
    cName: "Japan"
   }, {
    name: "Jām Sāhib",
    cName: "Pakistan"
   }, {
    name: "Athmuqam",
    cName: "Pakistan"
   }, {
    name: "Uto",
    cName: "Japan"
   }, {
    name: "Shiroi",
    cName: "Japan"
   }, {
    name: "Daur",
    cName: "Pakistan"
   }, {
    name: "Nago",
    cName: "Japan"
   }, {
    name: "Fujioka",
    cName: "Japan"
   }, {
    name: "Kanekomachi",
    cName: "Japan"
   }, {
    name: "Hangu",
    cName: "Pakistan"
   }, {
    name: "Chichibu",
    cName: "Japan"
   }, {
    name: "Kariya",
    cName: "Japan"
   }, {
    name: "Tosu",
    cName: "Japan"
   }, {
    name: "Jalālpur",
    cName: "Pakistan"
   }, {
    name: "Iyo",
    cName: "Japan"
   }, {
    name: "Mibu",
    cName: "Japan"
   }, {
    name: "Sūrāb",
    cName: "Pakistan"
   }, {
    name: "Nagato",
    cName: "Japan"
   }, {
    name: "Fukuechō",
    cName: "Japan"
   }, {
    name: "Obihiro",
    cName: "Japan"
   }, {
    name: "Tōbetsu",
    cName: "Japan"
   }, {
    name: "Ishiki",
    cName: "Japan"
   }, {
    name: "Ladhewāla Warāich",
    cName: "Pakistan"
   }, {
    name: "Hirakata",
    cName: "Japan"
   }, {
    name: "Suwa",
    cName: "Japan"
   }, {
    name: "Ichinohe",
    cName: "Japan"
   }, {
    name: "Iwakuni",
    cName: "Japan"
   }, {
    name: "Matsuyama",
    cName: "Japan"
   }, {
    name: "Kohāt",
    cName: "Pakistan"
   }, {
    name: "Al Khafjī",
    cName: "Saudi Arabia"
   }, {
    name: "Hamamatsu",
    cName: "Japan"
   }, {
    name: "Nishishinminato",
    cName: "Japan"
   }, {
    name: "Naukot",
    cName: "Pakistan"
   }, {
    name: "Toyooka",
    cName: "Japan"
   }, {
    name: "Suzaka",
    cName: "Japan"
   }, {
    name: "Shiozawa",
    cName: "Japan"
   }, {
    name: "Narutō",
    cName: "Japan"
   }, {
    name: "Sawara",
    cName: "Japan"
   }, {
    name: "Garhi Yāsīn",
    cName: "Pakistan"
   }, {
    name: "Ladhewāla Warāich",
    cName: "Pakistan"
   }, {
    name: "Jamshoro",
    cName: "Pakistan"
   }, {
    name: "Hasuda",
    cName: "Japan"
   }, {
    name: "Badīn",
    cName: "Pakistan"
   }, {
    name: "Islāmkot",
    cName: "Pakistan"
   }, {
    name: "Kabīrwāla",
    cName: "Pakistan"
   }, {
    name: "Kisarazu",
    cName: "Japan"
   }, {
    name: "Chikushino-shi",
    cName: "Japan"
   }, {
    name: "Fukura",
    cName: "Japan"
   }, {
    name: "Asahikawa",
    cName: "Japan"
   }, {
    name: "Tamana",
    cName: "Japan"
   }, {
    name: "Yukuhashi",
    cName: "Japan"
   }, {
    name: "Yashiro",
    cName: "Japan"
   }, {
    name: "Ādilpur",
    cName: "Pakistan"
   }, {
    name: "Kan’onjichō",
    cName: "Japan"
   }, {
    name: "Ōkawara",
    cName: "Japan"
   }, {
    name: "Ujiie",
    cName: "Japan"
   }, {
    name: "Komatsu",
    cName: "Japan"
   }, {
    name: "Yūki",
    cName: "Japan"
   }, {
    name: "Makubetsu",
    cName: "Japan"
   }, {
    name: "Annaka",
    cName: "Japan"
   }, {
    name: "Sakaidechō",
    cName: "Japan"
   }, {
    name: "Izumi",
    cName: "Japan"
   }, {
    name: "Uozu",
    cName: "Japan"
   }, {
    name: "Nagoya-shi",
    cName: "Japan"
   }, {
    name: "Ash Shafā",
    cName: "Saudi Arabia"
   }, {
    name: "Jōetsu",
    cName: "Japan"
   }, {
    name: "Suwa",
    cName: "Japan"
   }, {
    name: "Itsukaichi",
    cName: "Japan"
   }, {
    name: "Hino",
    cName: "Japan"
   }, {
    name: "Kōfu-shi",
    cName: "Japan"
   }, {
    name: "Shiogama",
    cName: "Japan"
   }, {
    name: "Sakaiminato",
    cName: "Japan"
   }, {
    name: "Abashiri",
    cName: "Japan"
   }, {
    name: "Ar Rass",
    cName: "Saudi Arabia"
   }, {
    name: "Kosai-shi",
    cName: "Japan"
   }, {
    name: "Akora",
    cName: "Pakistan"
   }, {
    name: "Kotri",
    cName: "Pakistan"
   }, {
    name: "Tabālah",
    cName: "Saudi Arabia"
   }, {
    name: "Hitachi",
    cName: "Japan"
   }, {
    name: "Basīrpur",
    cName: "Pakistan"
   }, {
    name: "New Mīrpur",
    cName: "Pakistan"
   }, {
    name: "Nishio",
    cName: "Japan"
   }, {
    name: "Sōja",
    cName: "Japan"
   }, {
    name: "Mach",
    cName: "Pakistan"
   }, {
    name: "Yazman",
    cName: "Pakistan"
   }, {
    name: "Lārkāna",
    cName: "Pakistan"
   }, {
    name: "Naka",
    cName: "Japan"
   }, {
    name: "Sanjwāl",
    cName: "Pakistan"
   }, {
    name: "Kurashiki",
    cName: "Japan"
   }, {
    name: "Yonezawa",
    cName: "Japan"
   }, {
    name: "Ādilpur",
    cName: "Pakistan"
   }, {
    name: "Takahagi",
    cName: "Japan"
   }, {
    name: "Mitsuke",
    cName: "Japan"
   }, {
    name: "Tārūt",
    cName: "Saudi Arabia"
   }]